sudo: false
language: perl
addons:
  apt:
    packages:
    - libdb-dev
services:
  - elasticsearch
install:
  - npm install -g eslint eslint eslint-plugin-react eslint-config-airbnb-es5 babel-eslint
  - bash setup.sh
  - curl -XDELETE 'http://localhost:9200/_all?pretty=true'
script:
  - bin/generate-elastic-search.pl --out test/volvox
  - eslint app.js test js
  - npm test
