sudo: false
language: perl
addons:
  apt:
    packages:
    - libdb-dev
services:
  - elasticsearch
cache:
  directories:
    - extlib/
install:
  - cpanm . -l extlib
  - npm install -g jshint
  - npm install
script:
  - bin/generate-elastic-search.pl --out test/volvox
  - jshint app.js test
  - mocha
